# Generated by Django 6.0.3 on 2026-05-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_image_complaintimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'قيد الانتظار'), ('in_progress', 'قيد المعالجة'), ('resolved', 'محلولة'), ('rejected', 'مرفوض')], default='new', max_length=20),
        ),
    ]
