# Generated by Django 6.0.3 on 2026-05-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
